In [1]:
import pandas as pd

In [2]:
recast_2018_0j = pd.read_pickle('./pp2BB0j_2018_13.pcl')
recast_2018_0j['Mode'] = '0 jet'
recast_2018_1j = pd.read_pickle('./pp2BB1j_2018_13_small_qcut.pcl')
recast_2018_1j['Mode'] = '1 jet (small qcut)'
recast_2018_1jb = pd.read_pickle('./pp2BB1j_2018_13.pcl')
recast_2018_1jb['Mode'] = '1 jet'
recast_2018 = pd.concat([recast_2018_0j,recast_2018_1j,recast_2018_1jb])
recast_2018.sort_values(['mLLP','mLSP','tau_ns','SR', 'Mode'],inplace=True,ignore_index=True)        

recast_2018 = recast_2018[recast_2018['SR'] == 'Trackless']

In [3]:
recast_2018[['Mode','SR','$N_s$','AccEff','mLLP','mLSP','tau_ns','robs','rexp','Total xsec (pb)']].T

,3,4,5,9,10,11,15,16,17,21,22,23
Mode,0 jet,1 jet,1 jet (small qcut),0 jet,1 jet,1 jet (small qcut),0 jet,1 jet,1 jet (small qcut),0 jet,1 jet,1 jet (small qcut)
SR,Trackless,Trackless,Trackless,Trackless,Trackless,Trackless,Trackless,Trackless,Trackless,Trackless,Trackless,Trackless
$N_s$,0.0,0.1844,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AccEff,0.0,0.000003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mLLP,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0
mLSP,450.0,450.0,450.0,475.0,475.0,475.0,485.0,485.0,485.0,490.0,490.0,490.0
tau_ns,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
robs,0.0,0.061467,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
rexp,0.0,0.054235,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Total xsec (pb),0.376727,0.383829,0.435515,0.376727,0.383483,0.431891,0.376727,0.383937,0.436077,0.376727,0.38303,0.437863

In [4]:
recast_2016_0j = pd.read_pickle('./pp2BB0j_2016_08.pcl')
recast_2016_0j['Mode'] = '0 jet'
recast_2016_1j = pd.read_pickle('./pp2BB1j_2016_08_small_qcut.pcl')
recast_2016_1j['Mode'] = '1 jet (small qcut)'
recast_2016_1jb = pd.read_pickle('./pp2BB1j_2016_08.pcl')
recast_2016_1jb['Mode'] = '1 jet'
recast_2016 = pd.concat([recast_2016_0j,recast_2016_1j,recast_2016_1jb])
recast_2016.sort_values(['mLLP','mLSP','tau_ns','Mode'],inplace=True,ignore_index=True)

In [5]:
recast_2016[['Mode','$N_s$','AccEff','mLLP','mLSP','tau_ns','robs','rexp','Total xsec (pb)']].T

,0,1,2,3,4,5,6,7,8,9,10,11
Mode,0 jet,1 jet,1 jet (small qcut),0 jet,1 jet,1 jet (small qcut),0 jet,1 jet,1 jet (small qcut),0 jet,1 jet,1 jet (small qcut)
$N_s$,6.527,8.377,9.538,0.2569,0.5373,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AccEff,0.000528,0.000665,0.000668,0.000021,0.000043,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mLLP,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0
mLSP,450.0,450.0,450.0,475.0,475.0,475.0,485.0,485.0,485.0,490.0,490.0,490.0
tau_ns,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
robs,2.175667,2.792333,3.179333,0.085633,0.1791,0.0,0.0,0.0,0.0,0.0,0.0,0.0
rexp,2.175667,2.792333,3.179333,0.085633,0.1791,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Total xsec (pb),0.376727,0.383829,0.435515,0.376727,0.383483,0.431891,0.376727,0.383937,0.436077,0.376727,0.38303,0.437863

In [6]:
recast_cms_0j = pd.read_pickle('./pp2BB0j_cms.pcl')
recast_cms_0j['Mode'] = '0 jet'
recast_cms_1j = pd.read_pickle('./pp2BB1j_cms_small_qcut.pcl')
recast_cms_1j['Mode'] = '1 jet (small qcut)'
recast_cms_1jb = pd.read_pickle('./pp2BB1j_cms.pcl')
recast_cms_1jb['Mode'] = '1 jet'
recast_cms = pd.concat([recast_cms_0j,recast_cms_1j,recast_cms_1jb])
recast_cms.sort_values(['mLLP','mLSP','tau_ns','Data-takingperiod','Mode'],inplace=True,ignore_index=True)        


recast_cms = recast_cms[recast_cms['Data-takingperiod'] == 2018]

In [7]:
recast_cms[['Mode','mLLP','mLSP','tau_ns','robs','rexp','Total xsec (pb)']].T

,6,7,8,15,16,17,24,25,26,33,34,35
Mode,0 jet,1 jet,1 jet (small qcut),0 jet,1 jet,1 jet (small qcut),0 jet,1 jet,1 jet (small qcut),0 jet,1 jet,1 jet (small qcut)
mLLP,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0
mLSP,450.0,450.0,450.0,475.0,475.0,475.0,485.0,485.0,485.0,490.0,490.0,490.0
tau_ns,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
robs,0.305748,NaN,0.345855,0.531385,NaN,1.214977,0.835962,NaN,1.183739,0.932305,NaN,1.694121
rexp,0.4422,NaN,0.558444,0.806574,NaN,1.64251,1.066601,NaN,2.081741,1.477183,NaN,2.392576
Total xsec (pb),0.376727,0.383829,0.435515,0.376727,0.383483,0.431891,0.376727,0.383937,0.436077,0.376727,0.38303,0.437863