In [2]:
import pandas as pd

In [3]:
recast_2018 = pd.read_pickle('./pp2BB1j_2018_13.pcl')
recast_2016 = pd.read_pickle('./pp2BB1j_2016_08.pcl')
# recast_monojet = pd.read_pickle()

In [4]:
recast_2016.T

,0,1,2,3
Luminosity (1/fb),32.8,32.8,32.8,32.8
$N_s$,8.377,0.5373,0.0,0.0
AccEff,0.000665,0.000043,0.0,0.0
Total,"(12590.0, 1.0)","(12580.0, 1.0)","(12590.0, 1.0)","(12560.0, 1.0)"
Jet+MET selection,"(935.5, 0.07431)","(726.6, 0.05776)","(679.1, 0.05393)","(638.0, 0.05079)"
DV selection,"(8.377, 0.0006654)","(0.5373, 4.272e-05)","(0.0, 0.0)","(0.0, 0.0)"
mLLP,500.0,500.0,500.0,500.0
mLSP,450.0,475.0,485.0,490.0
width,0.0,0.0,0.0,0.0
tau_ns,0.01,0.01,0.01,0.01
Total MC Events,17778,17762,17783,17741
Total xsec (pb),0.383829,0.383483,0.383937,0.38303
robs,2.792333,0.1791,0.0,0.0
rexp,2.792333,0.1791,0.0,0.0
kfactor,1.0,1.0,1.0,1.0

In [5]:
recast_2018.T

,0,1,2,3,4,5,6,7
Luminosity (1/fb),139.0,139.0,139.0,139.0,139.0,139.0,139.0,139.0
SR,HighPT,Trackless,HighPT,Trackless,HighPT,Trackless,HighPT,Trackless
$N_s$,0.0,0.1844,0.0,0.0,0.0,0.0,0.0,0.0
AccEff,0.0,0.000003,0.0,0.0,0.0,0.0,0.0,0.0
Total,"(53350.0, 1.0)","(53350.0, 1.0)","(53300.0, 1.0)","(53300.0, 1.0)","(53370.0, 1.0)","(53370.0, 1.0)","(53240.0, 1.0)","(53240.0, 1.0)"
Jet selection,"(12.0, 0.000225)","(105.0, 0.001969)","(0.0, 0.0)","(9.003, 0.0001689)","(0.0, 0.0)","(0.0, 0.0)","(6.002, 0.0001127)","(12.0, 0.0002255)"
DV selection,"(0.0, 0.0)","(0.1844, 3.456e-06)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)","(0.0, 0.0)"
mLLP,500.0,500.0,500.0,500.0,500.0,500.0,500.0,500.0
mLSP,450.0,450.0,475.0,475.0,485.0,485.0,490.0,490.0
width,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
tau_ns,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
Total MC Events,17778,17778,17762,17762,17783,17783,17741,17741
Total xsec (pb),0.383829,0.383829,0.383483,0.383483,0.383937,0.383937,0.38303,0.38303